# Generated by Django 5.2 on 2025-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_scenario_isdeleted_scenario_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
