# Generated by Django 5.1.3 on 2024-11-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='dateToExpire',
            field=models.DateTimeField(),
        ),
    ]
