# Generated by Django 5.1.3 on 2024-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_resetpasswordtoken_datetoexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='dateToExpire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
